#!/usr/bin/env node
/* Development-only server for the Monday visual review tool.
   Zero dependencies. Serves the repo over http:// (which the review page
   needs — a file:// iframe is an opaque origin and cannot be inspected),
   and provides the two endpoints the tool needs to persist work:

     POST /api/save   -> writes review/monday-review.json
     POST /api/apply  -> writes review/proposed-changes.css and returns it

   Nothing here writes to the production planner. Applying approved values is
   a separate, deliberate step described in review/README.md. */

const http = require('http');
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const PORT = Number(process.env.PORT || 5173);

const TYPES = {
  '.html': 'text/html; charset=utf-8', '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8', '.json': 'application/json; charset=utf-8',
  '.png': 'image/png', '.jpg': 'image/jpeg', '.svg': 'image/svg+xml',
  '.woff2': 'font/woff2', '.md': 'text/plain; charset=utf-8'
};

const readBody = req => new Promise((resolve, reject) => {
  let b = ''; req.on('data', c => { b += c; if (b.length > 4e6) req.destroy(); });
  req.on('end', () => resolve(b)); req.on('error', reject);
});

const send = (res, code, type, body) => {
  res.writeHead(code, { 'content-type': type, 'cache-control': 'no-store' });
  res.end(body);
};

/* Turns the review overrides into readable CSS. Values the production page
   computes at runtime (the title wash, the heading washes, the Notes rules)
   cannot be pinned by a plain rule — those are emitted as commented notes
   naming the parameter to change instead, rather than silently written as
   CSS that would be overwritten on load. */
const RUNTIME_OWNED = {
  'p1.titleWash': 'fitTitleWash() in monday/monday.js — TITLE_LEAD_MM, TITLE_BODY_FRAC, TITLE_H_FRAC',
  'wash': 'fitHeadingWashes() in monday/monday.js — WASH_LEAD_MM, WASH_BODY_FRAC, WASH_MIN/MAX_MM, WASH_H_FRAC'
};

function toCss(state) {
  const out = [
    '/* ==========================================================================',
    '   PROPOSED CHANGES — generated by the Monday visual review tool.',
    '   Not loaded by anything. Review each rule, then move what you approve into',
    `   monday/planner.css by hand.   ${new Date().toISOString()}`,
    '   ========================================================================== */',
    ''
  ];
  const entries = Object.entries(state.overrides || {});
  if (!entries.length) out.push('/* no overrides recorded */');

  for (const [key, o] of entries) {
    const props = Object.entries(o.css || {});
    if (!props.length) continue;
    out.push(`/* ${o.name} */`);
    const runtime = RUNTIME_OWNED[key] || (key.endsWith('.wash') ? RUNTIME_OWNED.wash : null);
    if (runtime) {
      out.push(`/* Runtime-owned geometry: set via ${runtime}`);
      out.push(`   ${o.selector}{ ${props.map(([k, v]) => `${k}:${v};`).join(' ')} } */`);
    } else {
      out.push(`${o.selector}{`);
      props.forEach(([k, v]) => out.push(`  ${k}:${v};`));
      out.push('}');
    }
    out.push('');
  }

  const pins = state.annotations || [];
  if (pins.length) {
    out.push('/* ---- notes left in review ----');
    pins.forEach(p => out.push(
      `   ${p.n}. page ${p.page} @ ${p.xMm}mm, ${p.yMm}mm` +
      (p.element ? ` [${p.element}]` : '') + ` — ${p.text}`));
    out.push('*/');
  }
  return out.join('\n') + '\n';
}

http.createServer(async (req, res) => {
  const url = new URL(req.url, 'http://localhost');

  if (req.method === 'POST' && url.pathname === '/api/save') {
    try {
      const state = JSON.parse(await readBody(req));
      state.savedAt = new Date().toISOString();
      const file = path.join(__dirname, 'monday-review.json');
      fs.writeFileSync(file, JSON.stringify(state, null, 2));
      return send(res, 200, TYPES['.json'],
        JSON.stringify({ ok: true, file: path.relative(ROOT, file) }));
    } catch (e) { return send(res, 400, 'text/plain', String(e)); }
  }

  if (req.method === 'POST' && url.pathname === '/api/apply') {
    try {
      const state = JSON.parse(await readBody(req));
      const css = toCss(state);
      const file = path.join(__dirname, 'proposed-changes.css');
      fs.writeFileSync(file, css);
      return send(res, 200, TYPES['.json'],
        JSON.stringify({ ok: true, file: path.relative(ROOT, file), css }));
    } catch (e) { return send(res, 400, 'text/plain', String(e)); }
  }

  if (req.method === 'GET' && url.pathname === '/api/state') {
    const file = path.join(__dirname, 'monday-review.json');
    return send(res, 200, TYPES['.json'],
      fs.existsSync(file) ? fs.readFileSync(file) : '{}');
  }

  // static
  let rel = decodeURIComponent(url.pathname);
  if (rel === '/') rel = '/review/monday.html';
  const file = path.join(ROOT, path.normalize(rel));
  if (!file.startsWith(ROOT) || !fs.existsSync(file) || fs.statSync(file).isDirectory())
    return send(res, 404, 'text/plain', 'not found: ' + rel);
  send(res, 200, TYPES[path.extname(file)] || 'application/octet-stream', fs.readFileSync(file));
}).listen(PORT, () => {
  console.log(`Monday visual review  ->  http://localhost:${PORT}/review/monday.html`);
  console.log('(development only — nothing here is part of the printable planner)');
});
